server:
  port: 3200

#debug: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security
    username: root
    password: malone
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


